[functions]
  directory = "netlify/functions"

[build]
  publish = "dist"
  command = "npm run build"

[dev]
  command = "npm run dev"
  targetPort = 4321
  port = 8888
  autoLaunch = false

[dev.environment]
  NODE_ENV = "development"

[template]
  required-extensions = ["supabase"]